services:
  db:
    image: postgres:15
    container_name: songrec-db
    restart: always
    environment:
      POSTGRES_USER: songrec
      POSTGRES_PASSWORD: songrecpass
      POSTGRES_DB: songrecdb
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
